apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ach-router-test
  annotations:
    argo.octopus.com/project: "ach-router"
    argo.octopus.com/environment: "test"
    argo.octopus.com/tenant: "_internal"
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusSolutionsEngineering/ghu-ach-router.git
     targetRevision: HEAD
     path: Kubernetes/Manifests/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
