apiVersion: apps/v1
kind: Deployment
metadata:
  name: ach-router-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ach-router-service
  template:
    metadata:
      labels:
        component: ach-router-service
    spec:
      containers:
        - name: ach-router
          image: octopussolutionsengineering/ghu-ach-router:25.12.05132406
          ports:
            - name: http-route
              containerPort: 80
